DB_HOST = 'localhost'
DB_PORT = 3306
DB_USER = 'dev'
DB_PASSWORD = 'pass'
DB_NAME = 'flowker'

FLOWKER_BASE_PATH = f'D:\\Projects\\flowker'
FLOWKER_CLIENT_PATH = f'{FLOWKER_BASE_PATH}\\client'
FLOWKER_SNAPSHOTS_PATH = f'{FLOWKER_CLIENT_PATH}\\snapshots'
FLOWKER_SCRIPTS_PATH = f'{FLOWKER_CLIENT_PATH}\\scripts'
FLOWKER_ENVIRONMENTS_PATH = f'{FLOWKER_CLIENT_PATH}\\environments'